; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
build_type = debug
upload_protocol = esptool
; change microcontroller
board_build.mcu = esp8266
; change MCU frequency
board_build.f_cpu = 160000000L
monitor_speed = 115200 

build_flags = -D PIO_FRAMEWORK_ARDUINO_ESP8266_GIT_REV="\"$(git rev-parse HEAD)\""


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_filters = esp32_exception_decoder
upload_protocol = esptool
; change microcontroller
board_build.mcu = esp32
; change MCU frequency
board_build.f_cpu = 240000000L
monitor_speed = 115200 

build_flags = -D PIO_FRAMEWORK_ARDUINO_ESP8266_GIT_REV="\"$(git rev-parse HEAD)\""

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_protocol = esptool
; MCU Settings
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
build_flags =
    -D ARDUINO_ARCH_ESP32
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit BNO08x